title: Quality of Space in Zurich
description: Zurich, a snapshot into Switzerland's economic heart, through the lens of Insurance data.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
